### ISSUE TITLE
[BUG] firefox: duplicate add-on ID found 

### ISSUE THREAD

**Issue by elijaholmos** [PlasmoHQ/bpp#83]
### What happened?

Hello, I've been testing BPP in my [open-source repository](https://github.com/elijaholmos/halo-discord-extension/tree/bpp), and I was able to successfully build & publish my extension to the Chrome and Edge stores. However, in this [failed workflow](https://github.com/elijaholmos/halo-discord-extension/actions/runs/3107951589/jobs/5036620981), Firefox throws a "duplicate add-on ID found" error. I intentionally leave the `firefox.extId` value blank in my `keys.json`, because my `manifest.json` contains the following:
```json
"browser_specific_settings": {
  "gecko": {
    "id": "hns@hns.com"
  }
}
  ```

After double-checking the schema for the keys file, it says to check the Technical Details section of my addon listing, which displays:
![image](https://user-images.githubusercontent.com/35435704/191836587-feaf8364-c576-4a55-b598-4ca796f196d8.png)

Is this an error on my end? Should I manually include the extension id of `hns@hns.com` in the BPP `keys.json`, or would that be redundant?

### Which browsers are you seeing the problem on?

Firefox

### Relevant log output

```Shell
Error: firefox: Step 1) Item ""hns@hns.com" (Halo Notification Service)": Duplicate add-on ID found.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I checked the [current issues](https://github.com/PlasmoHQ/bpp/issues?q=is%3Aopen+is%3Aissue+label%3Abug) for duplicate problems.

**Comment by louisgv** [comment]
Hi @elijaholmos, thanks for the issue report! 

I think there's actually a bug in the code that is now surfacing xD... apparently, the ID turned `undefined` when it's just an email. Someone submitted a patch last monday but I was busy last week so didn't get a chance to merge it. Will make a new release soon!

see: https://github.com/PlasmoHQ/mozilla-addons-api/pull/36

**Comment by louisgv** [comment]
@elijaholmos new version released, you can try rerun the v2 rolling version, or use a specific tagged version

**Comment by elijaholmos** [comment]
thank you! I'll try it out on my next extension release and let you know how it goes

**Comment by elijaholmos** [comment]
@louisgv cheers! Deployment was a success 🙂 thank you for fixing this quickly
