### ISSUE TITLE
[BUG] Failed to publish to chrome webstore

### ISSUE THREAD

**Issue by vernak2539** [PlasmoHQ/bpp#90]
### What happened?

I'm trying to publish my extension to the webstore and it's failing with the following message:

```
ERROR  | Error: chrome: Step 1) Item ""nflkcdlimipkgbacnfnhfecjgmojhklo" (__MSG_extensionName__)": Response code 400 (Bad Request)
```

I've not changed anything much recently (other than adding a couple new languages), but I've also not published an updated in a while.

I'm not sure what's going on. It's happening on both versions of my extension. 

You can see the extension [here](https://github.com/vernak2539/chrome-extension-google-doc-default-zoom), and the two builds here ([default](https://github.com/vernak2539/chrome-extension-google-doc-default-zoom/actions/runs/10723796448), [extended](https://github.com/vernak2539/chrome-extension-google-doc-default-zoom/actions/runs/10723796431)).

Any help would be much appreciated.

### Which browsers are you seeing the problem on?

Chrome

### Relevant log output

```Shell
ERROR  | Error: chrome: Step 1) Item ""nflkcdlimipkgbacnfnhfecjgmojhklo" (__MSG_extensionName__)": Response code 400 (Bad Request)

ERROR  | Error: chrome: Step 1) Item ""mdgikencgfhineaememjagpkiclbdkka" (__MSG_extensionNameExtended__)": Response code 400 (Bad Request)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I checked the [current issues](https://github.com/PlasmoHQ/bpp/issues?q=is%3Aopen+is%3Aissue+label%3Abug) for duplicate problems.

**Comment by vernak2539** [comment]
I figured out what this was. Since I've

>...also not published an updated in a while.

It looks like the refresh token was invalid. I had to:

1. `pnpm dlx gcp-refresh-token` in the directory of my `keys.json` file
2. Update the SUBMIT_KEYS environment variable used in the action to use the new refresh token
    ```
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
```

**Comment by j3soon** [comment]
Thank you so much for sharing! I just fixed my build by following your guide! ❤️

Related docs:
- https://github.com/PlasmoHQ/bms/blob/main/tokens.md
- https://github.com/PlasmoHQ/chrome-webstore-api/blob/main/token.md
